#!/usr/bin/env python3
"""Generate minimal TypeScript types from docs/openapi.yaml schemas."""

from __future__ import annotations

from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError as exc:  # pragma: no cover - developer setup guard
    raise SystemExit("PyYAML is required; run `make openapi-check` first") from exc


ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "docs" / "openapi.yaml"
OUTPUT = ROOT / "web" / "src" / "generated" / "api.ts"


def main() -> None:
    spec = yaml.safe_load(OPENAPI.read_text(encoding="utf-8"))
    schemas = spec["components"]["schemas"]
    lines = [
        "/* eslint-disable */",
        "// Generated by web/scripts/generate_api_types.py from docs/openapi.yaml.",
        "// Do not edit by hand.",
        "",
    ]
    for name, schema in schemas.items():
        lines.extend(render_schema(name, schema))
        lines.append("")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def render_schema(name: str, schema: dict[str, Any]) -> list[str]:
    if "allOf" in schema:
        parts = [schema_to_ts(part) for part in schema["allOf"]]
        return [f"export type {name} = " + " & ".join(parts) + ";"]
    if "enum" in schema:
        return [f"export type {name} = {literal_union(schema['enum'])};"]
    schema_type = schema.get("type")
    if schema_type == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        properties = schema.get("properties", {})
        for prop, prop_schema in properties.items():
            optional = "" if prop in required else "?"
            lines.append(f"  {prop}{optional}: {schema_to_ts(prop_schema)};")
        additional = schema.get("additionalProperties")
        if additional:
            lines.append(f"  [key: string]: {schema_to_ts(additional)};")
        lines.append("}")
        return lines
    return [f"export type {name} = {schema_to_ts(schema)};"]


def schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "allOf" in schema:
        return " & ".join(schema_to_ts(part) for part in schema["allOf"])
    if "const" in schema:
        return repr(schema["const"]).replace("'", '"')
    if "enum" in schema:
        return literal_union(schema["enum"])
    schema_type = schema.get("type")
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{schema_to_ts(schema.get('items', {}))}[]"
    if schema_type == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        parts: list[str] = []
        for prop, prop_schema in properties.items():
            optional = "" if prop in required else "?"
            parts.append(f"{prop}{optional}: {schema_to_ts(prop_schema)}")
        additional = schema.get("additionalProperties")
        if additional:
            parts.append(f"[key: string]: {schema_to_ts(additional)}")
        return "{ " + "; ".join(parts) + " }"
    return "unknown"


def literal_union(values: list[Any]) -> str:
    return " | ".join(repr(value).replace("'", '"') for value in values)


if __name__ == "__main__":
    main()
